.TH tiny 1 2025-04-26 BSD-0
.
.SH NAME
tiny \- tcp messenger server
.
.SH SYNOPSIS
.B tiny
\fBport\fR
[\fB\-h\fR]
.
.SH DESCRIPTION
.B tiny
a project to create the smallest and most accessible messenger
distributed in small parts that allow you to perform certain actions
.P
by default the messenger works without encryption
but if you have the necessary modules (\fBrsa\fR(3) \fBrsak\fR(1) \fBrsae\fR(1) \fBrsad\fR(1))
you can use the messenger with rsa encryption and certificates.
.
.SH OPTIONS
.TP
.BR \-h
prints usage to stdout.
.
.SH EXIT STATUS
.TP
.BR 0
program exited success.
.TP
.BR -1
program exited because received net error. 
.TP
.BR -2
program exited because argument format is invalid.
.
.SH EXAMPLE
.TP
.BR server
tiny \fIport\fR # open server at \fIport\fR 
.TP
.BR client
ncat \fIaddress port\fR # connect to server at \fIport\fR, for example we're using ncat,
you can use any other tcp text client
.
.SH SEE ALSO
\fBrsa\fR(3) \fBrsak\fR(1) \fBrsae\fR(1) \fBrsad\fR(1)
.
.SH AUTHOR
gimura <gimura0001@gmail.com>
