.TH tiny 1 2025-04-26 BSD-0
.
.SH NAME
tiny \- simple serial two size text messenger
.
.SH SYNOPSIS
.B tiny
\fBport\fR
[\fB\-h\fR]
.
.SH DESCRIPTION
.B tiny
is very small serial two side text messenger
.
.SH OPTIONS
.TP
.BR \-h
prints usage to stdout.
.
.SH EXIT STATUS
.TP
.BR 0
program exited success.
.TP
.BR -1
program exited because received net error. 
.TP
.BR -2
program exited because argument format is invalid.
.
.SH AUTHOR
gimura <gimura0001@gmail.com>
